### ISSUE TITLE
Task Force Radio not working in campaign mode

### ISSUE THREAD

**Issue by FromTheBedToTheFloor** [treendy/TRGM2.Malden#107]
Description: Task Force Arrowhead Radio works inconsistently. Sometimes it works in a single mission scenario and sometimes it does not. TFAR does not work at all in Campaign mode. When TFAR is non functioning the options menu is not visible or usable either, mod options are available however.

Reproduction:
Starting the game in campaign mode.

Expected result:
Teamspeak drags users into the appropriate channel (if available).
TFAR functions normally with proximity and radio functions available.

Actual result:
Teamspeak appears to function briefly by pulling people into the proper channel. But then promptly pulls them back to their original channel.
TFAR does not function at all, neither the proximity nor radio is present.

**Comment by treendy** [comment]
Thanks, I think this may be connected to the revive script.  I have had other reports of the menu missing if it is active, which may cause issues with TFAR too.

Ill be looking into this and will mark as closed once fixed (and not in release changes)
