### ISSUE TITLE
Virtual Arsenal and ACE "Call Transport Helicopter" Prompts Accumulate on Death

### ISSUE THREAD

**Issue by mitch-c-miller** [treendy/TRGM2.Malden#108]
If you die, multiple selections for "Call Transport Helicopter" appear in the ACE Self-Interact menu, and you have no way of getting rid of them.

- 0 deaths: 1 selection
- 1 death: 3 selection
- 2 deaths: 5 selection

Scroll wheel prompts for the virtual arsenal appear multiple times as well, with the number of prompts being personal deaths + 1.

Only tested on Malden with single missions, heavy missions, and with virtual arsenal enabled.

**Comment by treendy** [comment]
Thank you for letting me know, I should be able to find and fix this based on your information.  Will close card when fixed and include note in release log

**Comment by treendy** [comment]
This should now be ok, fixed in previous version which has now been published to all current TRGM maps
