### ISSUE TITLE
Player map markers get deleted immediately

### ISSUE THREAD

**Issue by TheLukio** [treendy/TRGM2.Malden#110]
So I've given your TRGM 2.0.20 a test run (impressive work I like it).

When I tried setting map markers - like Dot and text RC1 etc. the marker gets instantly deleted, no matter which channel I select. Group, Side, Vehicle etc. I rechecked server.cfg  and difficulty just to be sure that nothing is missing there. Somehow something is running or set that disables players from making custom markers.

Drawing on the map works and markers generated by missions work fine as well.

**Comment by treendy** [comment]
Take a look at the advanced settings when you start TRGM, there should be an option to enable map drawing.   By default, its set to only allow to draw in direct (but i do need to allow markers to be placed in direct though)
