### ISSUE TITLE
Aircraft Maintenance station

### ISSUE THREAD

**Issue by tundratier** [treendy/TRGM2.Malden#111]
I've created a local fork that adds an aircraft support station to the HQ airfield.

It can repair / refuel / rearm an aircraft and open a menu to change the plane's pylon loadout. (Using GOM Dynamic Loadout script)

If you think this is something that can be integrated into the mission, i'll make it pretty and create a PR.

**Comment by Xyaren** [comment]
Pylon Script should be disabled when using ACE: 
https://ace3mod.com/wiki/feature/pylons.html

**Comment by treendy** [comment]
Thanks for the suggestion : )  i dont think i will be adding this to the main version, so closing this issue for now (may change my mind in the future)
