### ISSUE TITLE
Virtual arsenal unavailable for teamleader

### ISSUE THREAD

**Issue by NikolaiVChr** [treendy/TRGM2.Malden#112]
We did  couple of missions (TRGM2 Takistan and Zargabad) in MP.

Teamleader could not access virtual arsenal even though that was selected inside adv. options.
The guy who hosted the server (non-dedicated) and was number 2 in the group, could access it.

We had CUP UK as friendly and CUP takistan militia as enemy.

**Comment by treendy** [comment]
Fixed for version 2.0.22
(this only happens for the box if you choose to start near the AO)
