### ISSUE TITLE
AI team-mates start with out of ammo

### ISSUE THREAD

**Issue by NikolaiVChr** [treendy/TRGM2.Malden#113]
We did a couple of missions (TRGM2 Takistan and Zargabad) in MP.
We had CUP UK as friendly and CUP takistan militia as enemy.

All AI teammates started complaining about no ammo right away when mission started.
And number 5, had ammo for a javelin in his backpack even though he had a titan launcher. And he offered no command to rearm even though he was right next to supply.

**Comment by treendy** [comment]
Thanks, this has been fixed and will be upload with version 2.0.22 soon : )
