### ISSUE TITLE
maybe have shrine thingy? when read, it shows total count of player killed (e.g. Treendy has been killed 3 times)

### ISSUE THREAD

**Issue by treendy** [treendy/TRGM2.Malden#49]
save this count on server???

**Comment by Xyaren** [comment]
create a "graveyard" near the base 😆 
,then spawn tombstones when a player dies the first time.

**Comment by treendy** [comment]
: )  I had the same idea... A game I use to love called "Cannon Fodder" had that feature... only problem is how many and having the right space for it
